###############################################################################
#
# Welcome!
#
# Update the settings below and in the following _data files:
# _data/course_outcomes.yml
# _data/textbooks.yml
# _data/instructors.yml
# _data/student_instructors.yml
#
###############################################################################

# Site settings - affect how your site is published
baseurl: "" # the subpath of your site, e.g. /blog
url: "mbmosman.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Color scheme based on http://flatuicolors.com/.
# Possible values:
#    - silver          - gold            - midnight
#    - green           - turquoise       - blue
#    - purple          - orange          - red
theme_color: silver

###############################################################################

###############################################################################
# The information below should not need to be modified.
###############################################################################

# Build settings
####################
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Collections - settings to publish the _collection folder content
####################
collections:
  modules:
    output: true
  outcomes:
    output: true
  readings:
    output: true
  experiences:
    output: true
  assessments:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "modules"
    values:
      layout: module_content
  -
    scope:
      path: ""
      type: "outcomes"
    values:
      layout: module_content
  -
    scope:
      path: ""
      type: "readings"
    values:
      layout: module_content
  -
    scope:
      path: ""
      type: "experiences"
    values:
      layout: module_content
  -
    scope:
      path: ""
      type: "assessments"
    values:
      layout: module_content
